# Generated by Django 5.0 on 2025-03-14 10:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_examnotification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examnotification',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='examnotification',
            name='start_time',
        ),
        migrations.RemoveField(
            model_name='examnotification',
            name='subject',
        ),
        migrations.AddField(
            model_name='examnotification',
            name='exam_name',
            field=models.CharField(default='Exam', max_length=100),
        ),
        migrations.AddField(
            model_name='examnotification',
            name='message',
            field=models.TextField(default='New exam has been scheduled.'),
        ),
        migrations.AlterField(
            model_name='examnotification',
            name='exam_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
