# Generated by Django 5.0 on 2025-03-28 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_remove_examnotification_end_time_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='examnotification',
            options={},
        ),
        migrations.RemoveField(
            model_name='examnotification',
            name='exam_date',
        ),
        migrations.RemoveField(
            model_name='examnotification',
            name='exam_name',
        ),
        migrations.AlterField(
            model_name='examnotification',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='examnotification',
            name='message',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='student',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
