# Generated by Django 3.2.25 on 2025-04-01 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_alter_examnotification_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='examnotification',
            name='exam_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='examnotification',
            name='exam_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
